apiVersion: v1
kind: Service
metadata:
  name: covid-stats-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: LoadBalancer
  selector:
    app: covid-stats
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-stats-deployment
  labels:
    app: covid-stats
spec:
#  strategy: {}
  selector:
    matchLabels:
      app: covid-stats
  replicas: 2
  template:
    metadata:
      labels:
        app: covid-stats
    spec:
      containers:
      - name: covid-stats
        image: covid-stats:latest
        ports:
        - containerPort: 8080
        env:
        - name: DEV_EXT_IP
          value: "97.113.223.41"